<h1>Question 2</h1>
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

<?php
	include_once "functions.php";

	$fibArray = getFibonacci(4000000);
	$onlyEven = array_filter($fibArray, "isEven");
	nicePrint($onlyEven);
	nicePrint("added: ".addArray($onlyEven));


